[PHP]
; Performances
memory_limit = 256M
max_execution_time = 60
max_input_vars = 3000
upload_max_filesize = 20M
post_max_size = 20M

; Affichage des erreurs (désactiver en prod)
display_errors = Off
log_errors = On
error_log = /var/log/php/error.log

; Timezone
date.timezone = Africa/Casablanca

; Sécurité
expose_php = Off
session.cookie_httponly = 1
session.cookie_secure = 0
session.use_strict_mode = 1

; Opcache (performances en prod)
opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.revalidate_freq = 0
opcache.fast_shutdown = 1
